import { NAV_ITEM_TYPE_ITEM, NAV_ITEM_TYPE_TITLE } from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'

const organizationsNavigationConfig: NavigationTree[] = [
    {
        key: 'org-dashboard',
        path: '/organizations/dashboard',
        title: 'Dashboard',
        translateKey: 'nav.dashboard',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['org_super_admin', 'org_member', 'org_admin'],
        subMenu: [],
    },
    {
        key: 'org-group-management',
        path: '',
        title: 'Organization',
        translateKey: 'nav.organization',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: ['org_super_admin', 'org_admin'],
        subMenu: [
            {
                key: 'org-workspaces',
                path: '/organizations/workspaces',
                title: 'Workspaces',
                translateKey: 'nav.workspaces',
                icon: 'workspace',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['org_super_admin', 'org_admin'],
                subMenu: [],
            },
            {
                key: 'org-team',
                path: '/organizations/team',
                title: 'Team Management',
                translateKey: 'nav.team',
                icon: 'team',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['org_super_admin', 'org_admin'],
                subMenu: [],
            },
            {
                key: 'org-projects',
                path: '/dashboard/projects',
                title: 'Projects',
                translateKey: 'nav.projects',
                icon: 'projects',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['org_super_admin', 'org_admin'],
                subMenu: [],
            },
            {
                key: 'org-roles',
                path: '/organizations/roles-permissions',
                title: 'Roles & Permissions',
                translateKey: 'nav.rolesPermissions',
                icon: 'shield',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['org_super_admin'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'org-group-ai',
        path: '',
        title: 'AI Services',
        translateKey: 'nav.aiServices',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: ['org_member', 'org_super_admin', 'org_admin'],
        subMenu: [
            {
                key: 'org-copilot-hub',
                path: '/organizations/copilot-hub',
                title: 'Copilot Hub',
                translateKey: 'nav.copilotHub',
                icon: 'copilotHub',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['org_member', 'org_super_admin', 'org_admin'],
                subMenu: [],
            },
            {
                key: 'org-aiplayground',
                path: '/organizations/ai-playground',
                title: 'AI Playground',
                translateKey: 'nav.aiPlayground',
                icon: 'aiplayground',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['org_super_admin', 'org_admin'],
                subMenu: [],
            },
            {
                key: 'org-model-library',
                path: '/organizations/model-library',
                title: 'Model Library',
                translateKey: 'nav.modelLibrary',
                icon: 'api_provider',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['org_super_admin'],
                subMenu: [],
            },
            {
                key: 'org-chat',
                path: '/organizations/chat',
                title: 'AI Chat',
                translateKey: 'nav.chats',
                icon: 'chat',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['org_member', 'org_super_admin', 'org_admin'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'org-group-billing',
        path: '',
        title: 'Financials',
        translateKey: 'nav.financials',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: ['org_super_admin', 'org_admin', 'org_member'],
        subMenu: [
            {
                key: 'org-credits-usage',
                path: '/organizations/credits-usage',
                title: 'Credits & Usage',
                translateKey: 'nav.creditsUsage',
                icon: 'revenue',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['org_super_admin'],
                subMenu: [],
            },
            {
                key: 'org-credits-usage-member',
                path: '/organizations/credit-usage',
                title: 'Credits & Usage',
                translateKey: 'nav.creditsUsageMember',
                icon: 'revenue',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['org_member', 'org_admin'],
                subMenu: [],
            },
            {
                key: 'org-bulk-credit',
                path: '/admin/credits/bulk',
                title: 'Distribute Credit',
                translateKey: 'nav.bulk-credit',
                icon: 'bulkCredit',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['org_super_admin'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'org-group-system',
        path: '',
        title: 'System & Security',
        translateKey: 'nav.system',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: ['org_super_admin', 'org_admin'],
        subMenu: [
            {
                key: 'org-api-keys',
                path: '/organizations/api-keys',
                title: 'API Keys',
                translateKey: 'nav.apiKeys',
                icon: 'key',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['org_super_admin', 'org_admin'],
                subMenu: [],
            },
            {
                key: 'org-audit-logs',
                path: '/organizations/audit-logs',
                title: 'Audit Logs',
                translateKey: 'nav.auditLogs',
                icon: 'security',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['org_super_admin', 'org_admin'],
                subMenu: [],
            },
            {
                key: 'org-settings',
                path: '/organizations/settings',
                title: 'Organization Settings',
                translateKey: 'nav.organizationSettings',
                icon: 'platformSettings',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['org_super_admin', 'org_admin'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'org-group-support',
        path: '',
        title: 'Support',
        translateKey: 'nav.support',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: ['org_member', 'org_super_admin', 'org_admin'],
        subMenu: [
            {
                key: 'org-help-center',
                path: '/organizations/help-center',
                title: 'Help Center',
                translateKey: 'nav.help-center',
                icon: 'chat',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['org_member', 'org_super_admin', 'org_admin'],
                subMenu: [],
            },
        ],
    },
]

export default organizationsNavigationConfig
