import React, { useState } from 'react'
import { Card, Pagination } from '@/components/ui'
import { NumericFormat } from 'react-number-format'
import { Building2 } from 'lucide-react'

// Types
import { WorkspaceRevenue } from '../../types'

interface WorkspacePerformanceTableProps {
    data: WorkspaceRevenue[]
}

/**
 * WorkspacePerformanceTable - Detailed breakdown of revenue generated by individual workspaces.
 * Includes revenue share visualization to quickly identify top contributors.
 */
export default function WorkspacePerformanceTable({ data }: WorkspacePerformanceTableProps) {
    const [currentPage, setCurrentPage] = useState(1)
    const pageSize = 5

    const paginatedData = data.slice((currentPage - 1) * pageSize, currentPage * pageSize)

    return (
        <Card className="p-0 border-none shadow-2xl shadow-gray-200/60 dark:shadow-none bg-white dark:bg-gray-900 rounded-[2.5rem] border border-gray-100 dark:border-gray-800 transition-all h-full flex flex-col overflow-hidden relative group">
            <header className="p-8 md:p-10 border-b border-gray-50 dark:border-gray-800 flex items-center justify-between bg-gray-50/30 dark:bg-gray-800/20">
                <div className="flex items-center gap-4">
                    <div className="w-12 h-12 bg-primary/10 rounded-2xl border border-primary/20 flex items-center justify-center">
                        <Building2 className="w-6 h-6 text-primary" />
                    </div>
                    <div>
                        <h3 className="text-lg font-black text-gray-900 dark:text-white">Workspace Earnings</h3>
                        <p className="text-[10px] font-black text-gray-400 mt-0.5">Performance Breakdown</p>
                    </div>
                </div>
            </header>

            <div className="p-4 md:p-6 flex-1">
                <div className="overflow-x-auto">
                    <table className="w-full">
                        <thead>
                            <tr className="border-b border-gray-50 dark:border-gray-800">
                                <th className="px-8 py-4 text-left">
                                    <span className="text-[10px] font-black text-gray-400">Workspace</span>
                                </th>
                                <th className="px-6 py-4 text-right">
                                    <span className="text-[10px] font-black text-gray-400">Revenue & Share</span>
                                </th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-gray-50 dark:divide-gray-800/50">
                            {paginatedData.map((item, idx) => (
                                <tr key={item.id || idx} className="group/row hover:bg-gray-50/50 dark:hover:bg-gray-800/20 transition-all duration-300">
                                    <td className="px-6 py-6">
                                        <div className="flex items-center gap-4">
                                            <div className="w-10 h-10 rounded-xl bg-gray-50 dark:bg-gray-800 border border-gray-100 dark:border-gray-700 flex items-center justify-center group-hover/row:bg-primary/5 group-hover/row:border-primary/20 transition-colors shadow-sm">
                                                <Building2 className="w-5 h-5 text-gray-400 group-hover/row:text-primary transition-colors" />
                                            </div>
                                            <div className="flex flex-col">
                                                <span className="text-sm text-gray-900 dark:text-gray-100 font-black group-hover/row:text-primary transition-colors">
                                                    {item.name}
                                                </span>
                                                <span className="text-[9px] font-bold text-gray-400 mt-0.5">Active Entity</span>
                                            </div>
                                        </div>
                                    </td>
                                    <td className="px-6 py-6 text-right">
                                        <div className="flex flex-col items-end gap-1.5">
                                            <div className="flex items-center gap-3">
                                                <span className="font-black text-gray-900 dark:text-white text-sm">
                                                    <NumericFormat
                                                        displayType="text"
                                                        value={item.revenue}
                                                        prefix="₦"
                                                        thousandSeparator={true}
                                                        decimalScale={0}
                                                    />
                                                </span>
                                                <div className="px-2.5 py-1 rounded-lg bg-primary/5 border border-primary/10 group-hover/row:bg-primary group-hover/row:text-white transition-all duration-500">
                                                    <span className="text-[10px] font-black">
                                                        {Math.ceil(item.share)}%
                                                    </span>
                                                </div>
                                            </div>
                                            <div className="w-32 h-1.5 bg-gray-100 dark:bg-gray-800 rounded-full overflow-hidden">
                                                <div
                                                    className="h-full bg-primary relative overflow-hidden"
                                                    style={{ width: `${Math.ceil(item.share)}%` }}
                                                >
                                                    <div className="absolute inset-0 bg-white/20 animate-shimmer" />
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </div>

            <div className="p-4 border-t border-gray-50 dark:border-gray-800 flex justify-end">
                <Pagination
                    currentPage={currentPage}
                    total={data.length}
                    pageSize={pageSize}
                    onChange={setCurrentPage}
                />
            </div>
        </Card>
    )
}
